# This workflow will run on commits and pull requests on the main branch and any tags pushed to the repository. It then runs the qa job which checks out the code, installs poetry in a Python 3.11 environment and installs the app dependencies. Finally, it runs the quality checks to make sure the code is formatted, passes static linting and type checking.

name: CI
on:
  push:
    branches: ["master"]
    tags: ["*"]
  pull_request:
    branches: ["master"]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry and poe
        run: |
          pipx install poetry
          pipx install poe
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install Dependencies
        run: poetry install --no-root --no-interaction

      - name: Formatting
        run: poe format
      - name: Linting
        run: poe lint
      - name: Static Type Checking
        run: poe typecheck

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry and poe
        run: |
          pipx install poetry
          pipx install poe
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install Dependencies
        run: poetry install --no-root --no-interaction

      - name: Test & Coverage
        run: poe test
      - name: Coverage Report
        run: |
          poetry run coverage xml
          poetry run coverage report -m
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
